# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171110_1925'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=b'(+38)', max_length=15),
        ),
    ]
